import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="header-wrap">
          <div className="header">
            <div className="header-logo">
              <img src="/Keylee_logo.png" />
            </div>
            <div className="header-nav">
              <div>
                <Link href="photography">photography</Link>
              </div>
              <div>
                <Link href="projects">projects</Link>
              </div>
              <div>
                <Link href="writing">writing</Link>
              </div>
              <div>
                <Link href="video">video</Link>
              </div>
              <div>
                <Link href="about-me">about me</Link>
              </div>
            </div>
            
          </div>
          <div>
              <p>x</p>
              <p>x</p>
              <p>x</p>
              <p>x</p>
              <p>x</p>

            </div>
        </div>

        <footer>
          <div className="footer-contact">
          <h2>Contact me</h2>

          </div>
        </footer>
        {children}</body>
    </html>
  );
}
